name: dart_coveralls
version: 0.6.0+4
author: Axel Christ <adracus@gmail.com>
description: |-
  Pub package to calculate coverage, format it
  to LCOV and send it to coveralls
homepage: https://github.com/block-forest/dart-coveralls
environment:
  sdk: '>=2.0.0-dev.64.1 <3.0.0'
dependencies:
  args: ^2.0.0
  coverage: ^1.0.1
  crypto: ^3.0.0
  file: ^6.1.0
  http: ^0.13.0
  logging: ^1.0.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  yaml: ^3.1.0
dev_dependencies:
  mockito: ^5.0.0
  test: ^1.16.5
executables:
  dart_coveralls: null
